# Generated by Django 6.0.2 on 2026-06-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp_cooldown_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_request_count',
            field=models.IntegerField(default=0),
        ),
    ]
